# Generated by Django 5.2.1 on 2025-05-16 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.CharField(max_length=255)),
                ('church_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.church')),
            ],
        ),
    ]
